### ISSUE TITLE
Render incomplete

### ISSUE THREAD

**Issue by lifez** [phuoc-ng/react-pdf-viewer#102]
I have a problem with rendering this file https://api.writershield.com/media/aaa.pdf

Pages look render incorrect and rotated at first load
<img width="432" alt="Screen Shot 2563-04-11 at 11 18 04" src="https://user-images.githubusercontent.com/2588927/79035221-8870a680-7be6-11ea-9959-c79b025d0315.png">
<img width="569" alt="Screen Shot 2563-04-11 at 11 17 39" src="https://user-images.githubusercontent.com/2588927/79035222-8c9cc400-7be6-11ea-93c1-897d523107fb.png">
<img width="470" alt="Screen Shot 2563-04-11 at 11 17 33" src="https://user-images.githubusercontent.com/2588927/79035224-8dcdf100-7be6-11ea-97ea-b4aaa2f75f3a.png">

Could you please help me please?

**Comment by phuoc-ng** [comment]
@lifez I couldn't download the file (https://api.writershield.com/media/aaa.pdf)?
Can you attach the file here?

**Comment by lifez** [comment]
@phuoc-ng I'm sorry. Could you please try this http://139.162.30.61:8005/media/aaa.pdf

**Comment by phuoc-ng** [comment]
@lifez Thanks. I downloaded the file. You can remove the file if you want.

**Comment by phuoc-ng** [comment]
@lifez This issue is fixed, and I will include the fix in the next version v1.6.0.

_Demo_

_View pages_
<img width="1048" alt="Screen Shot 2020-05-01 at 20 01 15" src="https://user-images.githubusercontent.com/57786711/80807706-16d5b800-8be8-11ea-8040-ed5905fb721b.png">

_Thumbnails in sidebar_
<img width="331" alt="Screen Shot 2020-05-01 at 20 04 08" src="https://user-images.githubusercontent.com/57786711/80807742-281ec480-8be8-11ea-96c9-527f9b5ea07c.png">

_In print mode_
<img width="1158" alt="Screen Shot 2020-05-01 at 20 07 56" src="https://user-images.githubusercontent.com/57786711/80807763-32d95980-8be8-11ea-805b-4f8d38fc1248.png">

**Comment by phuoc-ng** [comment]
@lifez The v1.6.0 is just [released](https://react-pdf-viewer.dev/updates). Please upgrade.

**Comment by lifez** [comment]
Thank you very much!
